version: '3.7'
services:
    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        ports:
            - "9000:8000"
        volumes:
            - ./app:/var/www/html

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: ChangeMe
            POSTGRES_USER: symfony
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432"
    phppgadmin:
        container_name: phppgadmin
        image: neimheadh/phppgadmin:latest
        ports:
            - "8080:80"
        environment:
            - POSTGRES_HOST=database
            - POSTGRES_PORT=5432
            - POSTGRES_USER=symfony
            - POSTGRES_PASS=ChangeMe
 


volumes:
  db-data:
